### PR TITLE
contrib: Use the readyz endpoint in startup probes

### LINKED ISSUE #1488: startupProbe and readinessProbe should use the readyz endpoint
### Description of Problem / Feature Request

Since the `/readyz` endpoint was [introduced](https://github.com/quay/clair/pull/1211) I would expect any checks on startup and readiness to use them but the openshift manifest does not.

### Expected Outcome

The `readinessProbe` and `startupProbe` to use the `/readyz` health endpoint.

### Actual Outcome

They use the `healthz` endpoint.

### Environment

- Clair version/image: main
- Clair client name/version: main
- Host OS: n/a
- Kernel (e.g. `uname -a`): n/a
- Kubernetes version (use `kubectl version`): all
- Network/Firewall setup: n/a

### PR DESCRIPTION
**Pull request by iainduncani**
Fixes #1488

### CODE REVIEW

**Comment by crozzy** [comment]
This is a great catch, one other thing to add here is that the startup probe should cover longer running DB migrations (possibly up to 30 mins) so we should set the `failureThreshold` and `periodSeconds` to cover that, something like:

```
  failureThreshold: 200
  periodSeconds: 10
```
?

**Comment by iainduncani** [comment]
@crozzy good point, I would probably make it an hour though as we've seen that length of time with some of the migrations so have updated the commit accordingly.

**Review by crozzy — DISMISSED** [review]

**Comment by crozzy** [comment]
@iainduncani can you please rebase this and we get it merged?

**Comment by iainduncani** [comment]
@crozzy done!

**Review by crozzy — APPROVED** [review]

**Pull request merged**
