### PR TITLE
keymanager: don't unconditionally log an error

### PR DESCRIPTION
**Pull request by hdonnay**
Signed-off-by: Hank Donnay <hdonnay@redhat.com>

### CODE REVIEW

**Review by ldelossa — COMMENTED** [review]
@hdonnay

Im happy to approve and merge this, but im under the impression the keymanager is going away all together. 

Still want this in?

**Comment by hdonnay** [comment]
We should either merge this or the complete removal, because an error every 5 minutes looks pretty rough in the logs

**Comment by ldelossa** [comment]
https://github.com/quay/clair/pull/1081

This will be ready for review tomorrow. Which will stop the error. 

Once thats merged, i had planned to removal all the actual code.

**Comment by hdonnay** [comment]
Okay, I'll close this and we'll land that tomorrow, then.

**Pull request closed without merging**
