### PR TITLE
ext/featurens: Add fedora regex matching

### PR DESCRIPTION
**Pull request by etsauer**
Ensure fedora images can be scanned

### CODE REVIEW

**Comment by jzelinskie** [comment]
Does fedora use something different to track vulns or the regular OVAL listings?

**Comment by etsauer** [comment]
@jzelinskie according to [this](https://fedoraproject.org/wiki/Features/OpenSCAP) it looks to be the same.

**Comment by etsauer** [comment]
bump.

**Comment by jzelinskie** [comment]
Hey there, I'm just double checking on whether or not we should be pulling data from here or it's better to get it from another place.

**Comment by jzelinskie** [comment]
So I poked around and got some information from @brianredbeard.
If we're going to detect Fedora, we should also track vulnerabilities from Fedora by using their official database for tracking content, [Bodhi](https://bodhi.fedoraproject.org/updates/?type=security)

[FedMsg](https://fedora-fedmsg.readthedocs.io/en/latest) is also another tool for tracking Fedora content we should explore, although it looks like pure Python.

**Comment by jam01** [comment]
Bump... Can we reopen this? I've built a couple of images based on fedora that'd are failing to scan.

**Comment by jzelinskie** [comment]
This PR needs more than just identifying the Fedora namespace. It also needs to include a vulnsrc for what Fedora is using to track vulnerabilities.

**Comment by urbaniak** [comment]
Any updates on supporting Fedora?

**Comment by ldelossa** [comment]
Fedora is a bleeding edge distribution with no security tracker. Fedora support is a non-goal.

**Pull request closed without merging**
