### PR TITLE
Update the Ingress to use apiVersion: networking.k8s.io/v1beta1

### PR DESCRIPTION
**Pull request by mtougeron**
This PR updates the `Ingress` so that it is Kubernetes 1.16 compatible.

### CODE REVIEW

**Comment by mtougeron** [comment]
Hey all, just wanted to ping you and see if this PR is okay or not. Thanks

**Review by ldelossa — APPROVED** [review]
LGTM :+1:

**Comment by ldelossa** [comment]
@mtougeron thanks for this.

**Comment by mtougeron** [comment]
Thanks!

**Pull request merged**
