### PR TITLE
config: allow disabling notifier

### PR DESCRIPTION
**Pull request by hdonnay**
This commit allows for the notifier to be disabled in combo mode by
removing all configuration stanzas. A log line is printed to notify the
operator, although this shouldn't affect operation, as nothing was
configured to happen in this case.

The behavior of notifier mode is slightly altered: it will now refuse to
start if unconfigured.

Signed-off-by: Hank Donnay <hdonnay@redhat.com>

### CODE REVIEW

**Review by ldelossa — COMMENTED** [review]
Can you confirm this works in both combo and non combo modes

**Review by ldelossa — COMMENTED** [review]
Why do we treat notifier special here in combo mode? Should we make other modes optional as well?

**Comment by alecmerdler** [comment]
What about having incremental backoff of delivery failures instead?

**Comment by ldelossa** [comment]
@hdonnay  Whats that status of this?

**Pull request closed without merging**
