### PR TITLE
Configurable package endpoint URLs

### PR DESCRIPTION
**Pull request by MackJM**
- Added 'endpoints' under updater in the config
- Endpoints are set at init, or the default is used if blank or omited
- Added SetEndpointURL to vulnsrc and vulnmdsrc
- Added example endpoint config to config.example.yaml

### CODE REVIEW

**Comment by MackJM** [comment]
@jzelinskie any thoughts on this?

**Comment by reasonerjt** [comment]
This change is valuable for 2.0 to mitigate the impact when the endpoint of vuln data updates.

**Comment by jzelinskie** [comment]
So, I feel like this is reasonable for v2.x, but not for v3.x because there are no guarantees in the future that every vulnsrc can be represented by a URL prefix.

**Comment by MackJM** [comment]
@jzelinskie I believe it should be good to go.

**Comment by MackJM** [comment]
@jzelinskie I dunno if you have time but I'd love to close this.

**Pull request closed without merging**
