### PR TITLE
Added Mitre as CVE metadata source

### PR DESCRIPTION
**Pull request by jsfan**
Implements feature request #405

The metadata added are a list of reference URLs (if available for a specific vulnerability).

### CODE REVIEW

**Comment by jsfan** [comment]
This PR of mine has been sitting here for a number of months now. I'm keen to get it merged. So, is there anything I can change to make this valuable?

**Comment by rmkanda** [comment]
@ldelossa @jsfan Reviving the PR

**Comment by ldelossa** [comment]
@jsfan I am OK with merging this however be aware that ClairV3 is in maintenance and we are working on ClairV4 and the ClairCore project. Support for ClairV3 will be slower then the new upcoming version.

**Review by ldelossa — APPROVED** [review]
Thanks!

**Pull request merged**
