### PR TITLE
Notification: Add new stomp notifier

### PR DESCRIPTION
**Pull request by Allda**
Stomp protocol is capable to send messages/notification to message bus.
https://stomp.github.io/

The code is tested on Activemq messages bus. The code also supports
multiple brokers. In case one of them fails it can recover connection
and send a message to another one.

### CODE REVIEW

**Comment by jzelinskie** [comment]
I'm honestly curious how many other users are interested in this before I commit to maintaining it upstream. It seems like it gets us a wide variety of message queues, but I haven't really seen any requests for this functionality until now.

**Comment by Allda** [comment]
Stomp is a good way of sending messages to message bus. We are using it internally in Red Hat and I thought somebody else would be interested too.

**Comment by KeyboardNerd** [comment]
test?

**Comment by Allda** [comment]
I will add a test during next week.

**Comment by Allda** [comment]
@KeyboardNerd I added a unit test. Can you please review it again? Thanks

**Comment by Allda** [comment]
@ldelossa @hdonnay Hi guys, could you please take a look at this PR. Thanks

**Review by ldelossa — APPROVED** [review]
:+1:

**Pull request merged**
