### PR TITLE
http: rate limit index report requests

### PR DESCRIPTION
**Pull request by crozzy**
Added a basic rate limiter that will keep concurrent connections
limited and return a 429 if they go above.

Signed-off-by: crozzy <joseph.crosland@gmail.com>

### CODE REVIEW

**Comment by hdonnay** [comment]
There's also the package https://pkg.go.dev/golang.org/x/time/rate, which is getting used in the client rate-limiter.

**Review by luze560715 — DISMISSED** [review]

**Comment by crozzy** [comment]
> There's also the package https://pkg.go.dev/golang.org/x/time/rate, which is getting used in the client rate-limiter.

Yeah, I thought about that, the implementation could look something like this:
```go
type RateLimitMiddleware struct {
	limiter *rate.Limiter
}

func NewRateLimitMiddleware(maxConcurrent int) *RateLimitMiddleware {
	rlm := &RateLimitMiddleware{
		limiter: rate.NewLimiter(rate.Limit(maxConcurrent), maxConcurrent),
	}
	return rlm
}

func (rlm *RateLimitMiddleware) Handler(endpoint string, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if rlm.limiter == nil {
			next.ServeHTTP(w, r)
			return
		}

		if !rlm.limiter.Allow() {
			rateLimitedCounter.WithLabelValues(endpoint).Add(1)
			resp := &jsonerr.Response{
				Code:    "too-many-requests",
				Message: "server handling too many requests",
			}
			jsonerr.Error(w, resp, http.StatusTooManyRequests)
			return
		}

		next.ServeHTTP(w, r)
	})
}
```
The question is, do we want requests/sec to be limited, or concurrent requests to be limited. I'm not entirely sure.

**Comment by hdonnay** [comment]
Ah, that's a good point; the request counting scheme means we could, in theory, serve more requests in the same amount of time.

**Comment by crozzy** [comment]
@hdonnay I'm taking this out of draft, one thing that is still on the table is either going with the predefined number (like now), or derive the number from the size of the container and the config having an on/off switch instead of a number.

**Review by hdonnay — DISMISSED** [review]
LGTM

Re: sizing: It'd be nice for the default to have some intelligent limit (that an operator can then override by doing >0 or disable entirely by going <0) but I don't have a good idea how, yet. Probably some heuristic with GOMAXPROCS as the input.

**Review by hdonnay — APPROVED** [review]

**Pull request merged**
