### PR TITLE
adding publisher datetime and updating nvd feed download

### PR DESCRIPTION
**Pull request by ErikThoreson**
nvd.go and xml.go: added publisher datetime from xml feed and updated the XML feed download to complete before moving onto downloading the next feed

Reason:
The NVD site frequently resets connections when downloading the feeds if they are not downloaded in a timely manner. When all the feeds are requested at once but then not downloaded immediately the NVD site will reset the connection. It is more reliable to download each after making the request instead of opening all the connections then downloading them one at a time.
Also added is the Publication Datetime from the XML. This field is useful for compliance as many vulnerability programs for PCI base their remediation priority off this date field.

Example feed error:
{"Event":"could not decode NVD data feed","Level":"error","Location":"nvd.go:93","Time":"2017-08-25 18:48:15.515078","data feed name":"2014","error":"read tcp 192.168.10.9:54476-\u003e129.6.13.177:443: read: connection reset by peer"}

NOTE: this is a back port of the changes here https://github.com/coreos/clair/pull/571 for version 2.x.x

### CODE REVIEW

**Comment by ErikThoreson** [comment]
@jzelinskie any chance you can have a peek at this one?

**Comment by ldelossa** [comment]
@ErikThoreson  I'm not exactly following your second point in this PR. 

The datafeed retrieval (https://github.com/coreos/clair/blob/master/ext/vulnmdsrc/nvd/nvd.go#L235-L239) happens in a separate http connection then the downloading of the feed (https://github.com/coreos/clair/blob/master/ext/vulnmdsrc/nvd/nvd.go#L198-L203)

At first glance I do not see any "holding open" of connections between retrieving feeds and downloading them.

**Comment by ErikThoreson** [comment]
@ldelossa you're looking at master. This PR is for v2. These change were made to master awhile ago in this PR. 

https://github.com/coreos/clair/pull/571

**Comment by ldelossa** [comment]
@ErikThoreson :+1:

**Review by ldelossa — APPROVED** [review]

**Comment by ErikThoreson** [comment]
@ldelossa thanks for the merge. will this get included in the next v2.x.x release?

**Pull request merged**
