### PR TITLE
README: include data licenses for data sources

### PR DESCRIPTION
**Pull request by jzelinskie**

### CODE REVIEW

**Comment by Quentin-M** [comment]
You mixed up licenses.

**Comment by Quentin-M** [comment]
Also, let's wait for Ubuntu's answer.

**Comment by jzelinskie** [comment]
yep, thx

**Comment by Quentin-M** [comment]
Ubuntu’s vulnerabilities seem to be licensed under GNU GPL v2 (https://code.launchpad.net/ubuntu-cve-tracker).

**Comment by Quentin-M** [comment]
LGTM as soon as Ubuntu's license is listed. Thanks!

**Comment by jzelinskie** [comment]
ptal

**Comment by Quentin-M** [comment]
LGTM

**Pull request merged**
