### PR TITLE
Fix Spelling Error

### PR DESCRIPTION
**Pull request by ceagan**

### CODE REVIEW

**Review by ldelossa — DISMISSED** [review]
Thanks!

**Comment by ldelossa** [comment]
@ceagan can you sign this commit with a "-s". This will allow the DCO bot to accept the PR.

**Comment by crozzy** [comment]
Hi @ceagan, https://github.com/quay/clair/blob/main/.github/CONTRIBUTING.md#format-of-the-commit-message the commit message also needs to be in the format outlined here so it's consistent with the rest of the history.

The same goes for the merge commit, but probably rebasing with `main` is a better option to avoid the extra commit in the history.

Thanks

**Comment by crozzy** [comment]
fixed in https://github.com/quay/clair/pull/1348

**Pull request closed without merging**
