### PR TITLE
httptransport: add mime type to indexer and matcher handler

### PR DESCRIPTION
**Pull request by arajkumar**
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
Thx

**Comment by ldelossa** [comment]
@hdonnay can you fact check me on this, I approved, but I know that go http lib does "some kind of" content type detection if you don't provide the content type. Not sure if "application/json" is one ?

**Comment by hdonnay** [comment]
It only does content-type sniffing for functions like http.ServeFile, I think.

Regardless, this seems alright, as we've essentially committed to `application/json` meaning our v1 datatypes elsewhere.

**Comment by ldelossa** [comment]
sounds good to me. @arajkumar rebase and we'll merge. Thanks.

**Review by ldelossa — DISMISSED** [review]

**Comment by ldelossa** [comment]
@arajkumar  needs rebase

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
