### PR TITLE
docs: move to standard Documentation dir

### PR DESCRIPTION
**Pull request by jzelinskie**
When I can, I'll follow up with a new setup docs. For now, let's just try to get what we've got onto the website.

### CODE REVIEW

**Comment by robszumski** [comment]
LGTM. Might make sense to have a link in those readmes to the docs.

**Comment by jgsqware** [comment]
agreed with the link in the main Readme

**Comment by Quentin-M** [comment]
LGTM as soon as the links in the main README.md are updated too.

**Comment by jzelinskie** [comment]
Rather than linking to the docs for the particular hash, I've instead linked to where the latest stable documentation will be on coreos.com.

Hopefully this is guide people away from using the docs on master and rather using the docs for the latest stable release.

It'll be more clear when we shrink our readme and break down some of the information into their own docs.

**Comment by jgsqware** [comment]
LGTM

Le mer. 24 août 2016 17:20, Jimmy Zelinskie notifications@github.com a
écrit :

**Pull request merged**
