### PR TITLE
Added vulnerability source URL to the config file

### PR DESCRIPTION
**Pull request by MackJM**
- The source URL for updaters in the vulnerability source can now change through the config
- Changed the array of enabledUpdaters to a map
- When no url is present to the default is still used

### CODE REVIEW

**Comment by MackJM** [comment]
I'm working on getting this working in release-2.0 as well

**Comment by jzelinskie** [comment]
I believe there used to be another PR implementing this behavior in the past. I want to dig up that discussion so that I can see if there was anything useful.

**Comment by MackJM** [comment]
@jzelinskie sounds good, I wasn't sure this was the best way of doing it. But it was the best I could come up with at the time.

**Comment by MackJM** [comment]
I'm going to rework this a little better, and add nvd source.

**Pull request closed without merging**
