### PR TITLE
chore: fix yaml file indentation issue

### PR DESCRIPTION
**Pull request by chenrui333**
Fix the yaml config file syntax issue `failed to decode yaml config: yaml`

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
Thanks a lot for this.

**Comment by chenrui333** [comment]
@ldelossa 👋  it looks like this is never got released as part of 4.0.1 and 4.0.2 releases?

relates to https://github.com/Homebrew/homebrew-core/pull/71437

**Comment by ldelossa** [comment]
It did not, latest back ports were critical panic fixes. I'll look at getting this in soon

**Comment by chenrui333** [comment]
I see, thanks!

**Comment by chenrui333** [comment]
👋 It looks like this PR still did not get ported back to 4.0.x release line?

relates to Homebrew/homebrew-core#75334

**Pull request merged**
