### PR TITLE
Add dumb-init to Dockerfile Entrypoint

### LINKED ISSUE #630: Backport #477 in the 2.0.x release branch
### Description of Problem / Feature Request

We just run into #441. The issue has been fixed with #477 almost a year ago in master.

Can we please backport this so that this issue is mitigated in production deployments? It should not introduce any incompatibilities or functional changes (besides that the container doesn't create thousands of zombies anymore.)

### Expected Outcome
No zombies

### Actual Outcome
Zombies!

### Environment

- Clair version/image: v2.0.4
- Clair client name/version: N/A
- Host OS: CoreOS
- Kernel (e.g. `uname -a`): 4.14.48-coreos-r2
- Kubernetes version (use `kubectl version`): 1.7.5
- Helm version (use `helm version`): 1.10
- Network/Firewall setup: N/A

### PR DESCRIPTION
**Pull request by roxspring**
Cherry picked commits from #477 in order to properly address #441 in 2.0 versions.

> This allows for proper zombie process reaping. See discussion in #441

Closes #630

### CODE REVIEW

**Comment by jzelinskie** [comment]
Isn't another workaround for this using `tini` init built into docker? Try passing the `--init` flag to `docker run`.

If this is sufficient (which I believe it is), we should just update the docs.

**Comment by roxspring** [comment]
The `--init` flag might be a solution when running vanilla docker but I don't think this can be specified when running in Kubernetes.

Given that the this is simply a back port of the solution already merged into master, does it really make sense to solve the problem differently here?

**Comment by jzelinskie** [comment]
I think that's a pretty good argument.

Thanks for your patience, and quick response.

**Review by jzelinskie — APPROVED** [review]

**Comment by roxspring** [comment]
No problem. Thanks for the great tool!

Any idea when this might get into a new v2.0.x release?
(or if there's anything I can do to help make it happen)

**Pull request merged**
