### PR TITLE
Extend integration tests for AMQP and STOMP deliverers

### PR DESCRIPTION
**Pull request by jan-zmeskal**
This is just a draft PR, please don't review just yet.

Signed-off-by: Jan Zmeskal <jzmeskal@redhat.com>

### CODE REVIEW

**Review by ldelossa — COMMENTED** [review]
Looks like the right approach. Do these tests pass?

**Comment by jan-zmeskal** [comment]
@ldelossa Yes, they do.

**Comment by ldelossa** [comment]
looks good so far!

**Comment by jan-zmeskal** [comment]
@ldelossa @hdonnay Ready for review, please take a look.

**Review by ldelossa — DISMISSED** [review]
Lgtm. This is great. Thanks

**Comment by jan-zmeskal** [comment]
@ldelossa Thank you for the review, rebased

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
