### PR TITLE
Adding production users and integrations pages

### PR DESCRIPTION
**Pull request by pgburt**
Production-users and Integrations pages, per the request from @philips

### CODE REVIEW

**Comment by philips** [comment]
Can you move the stuff from the bottom of the README into integratoins?

**Comment by Quentin-M** [comment]
I feel like these documents should not be merged empty.. There are several production users and projects integrating with Clair out there (not necessarily listed in the README).

**Comment by pgburt** [comment]
Added some content @Quentin-M @philips @jzelinskie.

Also modified the links on README to point to new docs. 

LMK what ya think.

Edit: woops, I need to update the README links. They lead to a 404 atm D:

**Review by philips — APPROVED** [review]

**Comment by Quentin-M** [comment]
@philips Just a few minutes of research this morning ...

Recent integrations:
- Zendesk Samson https://github.com/zendesk/samson/commit/7f788d6e77e6b62bf5671090ca8b76c6ecfa5cd4
- Drone CI: https://github.com/drone/drone-plugin-index/commit/d594bee137142e22b647579575b625d9c18bd5b3
- STUPS' Pier One Registry: https://github.com/zalando-stups/pierone

Mentions/Discussions for future integrations:
- VMWare's Harbor Registry: https://github.com/vmware/harbor/issues/1411
- BlackArch pentesting OS: https://github.com/BlackArch/blackarch/issues/1378
- Empire PAAS: https://github.com/remind101/empire/issues/999 (proposed by main maintainer)
- SUSE Portus: https://github.com/SUSE/Portus/issues/1135 (proposed by PM Director, Oracle Linux)
- Federalist (interface for publishing static government websites): https://github.com/18F/federalist/issues/556

**Pull request merged**
