### PR TITLE
updaters: plumb update retention in

### PR DESCRIPTION
**Pull request by ldelossa**
Signed-off-by: ldelossa <ldelossa@redhat.com>

### CODE REVIEW

**Review by hdonnay — CHANGES_REQUESTED** [review]
If the `Validate` function now sets defaults, the signature needs to change to take a pointer and the documentation should note that it may modify the passed structure.

**Comment by hdonnay** [comment]
Also, should these changes be picked onto the stable branch?

**Comment by ldelossa** [comment]
@hdonnay reworked the config a bit to make "per stanza" validators. 

As far as back-porting. Let's cut v4.1.0 and then do a compare against stable `release 4.0` then decide what needs to get back ported and what does not.

**Comment by ldelossa** [comment]
Note: only backport documentation fixes

**Review by hdonnay — APPROVED** [review]
lgtm

**Pull request merged**
