### PR TITLE
cicd: fix docker test

### PR DESCRIPTION
**Pull request by hdonnay**
GitHub Actions is the worst CI except for every other CI service.

### CODE REVIEW

**Comment by hdonnay** [comment]
Waiting for quay/claircore#1314 to be merged, then I'll double check that these changes make everything green again.

**Review by crozzy — DISMISSED** [review]

**Comment by hdonnay** [comment]
Now waiting on quay/claircore#1319 because there was another, different bug.

**Comment by hdonnay** [comment]
:tada: https://github.com/quay/clair/actions/runs/8664140305

**Comment by hdonnay** [comment]
I guess this didn't have any changes in this repo, but please push the button again

**Review by crozzy — APPROVED** [review]

**Pull request merged**
