### PR TITLE
Update integrations.md

### PR DESCRIPTION
**Pull request by CMYanko**
Adding Sonatype's integration with Clair to the list

### CODE REVIEW

**Comment by ldelossa** [comment]
@CMYanko hey there,

You will sign off on this commit. 
```
git commit --amend --signoff
```
then force push back to your branch.

**Comment by CMYanko** [comment]
Done, do I need to re-request the pull?

**Comment by ldelossa** [comment]
@CMYanko going to close this, please open again with a signed commit.

**Comment by CMYanko** [comment]
Why would this just get closed?

**Comment by ldelossa** [comment]
@CMYanko 

You must submit your commit with the "signoff" flag so DCO but does not complain.

**Pull request closed without merging**
