### PR TITLE
admin: add pre v4.8.0 admin command to delete OVAL vulns

### PR DESCRIPTION
**Pull request by crozzy**
The migration to delete OVAL vulnerabilities can take a while (10 mins plus depending on resources). This patch adds a command to pre-delete the vulnerabilities after adding the migration version entry.

### CODE REVIEW

**Comment by hdonnay** [comment]
I think this should be a pre job to make an entry in the migrations table, and a post job to do the deletions.

As is, this leaves a (larger) period of time where there will be incorrect results for RHEL.

**Comment by crozzy** [comment]
> I think this should be a pre job to make an entry in the migrations table, and a post job to do the deletions.
> 
> As is, this leaves a (larger) period of time where there will be incorrect results for RHEL.

We could do it like that, the worry I'd have is that there would be a period where we'll be pulling a bunch of vulnerabilities back as the query will be looser and we'll be pulling the OVAL and VEX vulns. We could try and deploy everything together ( admin task and version switch) to reduce that period.

**Comment by hdonnay** [comment]
I'd rather pull "extra" results during the manual migration window than be guaranteed to produce false negatives.

**Comment by crozzy** [comment]
Split into 2

**Review by hdonnay — APPROVED** [review]

**Pull request merged**
