### PR TITLE
Fix for "race" in analyze-local-images

### LINKED ISSUE #27: analyze-local-images: says “the resource cannot be found”
I was trying to use the new `analyze-local-images` program, but it doesn’t seem to work for me:

In one terminal, I start clair:

```
$ docker run -it -p 6060:6060 -p 6061:6061 quay.io/coreos/clair --db-path=/db/bolt
2015-11-23 21:37:05.493710 I | database: database at /db/bolt does not exist yet, creating it
2015-11-23 21:37:05.499966 I | api: starting API on port 6060.
2015-11-23 21:37:05.500029 I | updater: updater service started. lock identifier: 78143d76-b946-45b5-86d5-e80dd72c9dce
2015-11-23 21:37:05.500291 I | api: starting Health API on port 6061.
2015-11-23 21:37:05.502117 I | updater: updating vulnerabilities
2015-11-23 21:37:05.502210 I | updater/fetchers: fetching Debian vulneratibilities
2015-11-23 21:37:05.502467 I | updater/fetchers: fetching Ubuntu vulneratibilities
2015-11-23 21:37:05.502744 I | updater/fetchers: fetching Red Hat vulneratibilities
2015-11-23 21:40:37.745528 E | worker: layer cf2616975b4a3cba083ca99bc3f0bf25f5f528c3c52be1596b30f60b0b1c37ff: failed to extract data from /tmp/analyze-local-image-197689302/cf2616975b4a3cba083ca99bc3f0bf25f5f528c3c52be1596b30f60b0b1c37ff/layer.tar: the resource cannot be found
2015-11-23 21:40:37.745605 I | api: 404 POST /v1/layers (390.349µs)
2015-11-23 21:40:58.800581 E | worker: layer 902b87aaaec929e80541486828959f14fa061f529ad7f37ab300d4ef9f3a0dbf: failed to extract data from /tmp/analyze-local-image-040123037/902b87aaaec929e80541486828959f14fa061f529ad7f37ab300d4ef9f3a0dbf/layer.tar: the resource cannot be found
2015-11-23 21:40:58.800611 I | api: 404 POST /v1/layers (175.692µs)
```

In another one, I run analyze-local-images:

```
$ analyze-local-images debian:jessie      
Saving debian:jessie
Getting image's history
Analyzing 2 layers
- Analyzing 902b87aaaec929e80541486828959f14fa061f529ad7f37ab300d4ef9f3a0dbf
2015/11/23 22:40:58 - Could not analyze layer: Got response 404 with message {"Message":"the resource cannot be found"}
```

My docker version:

```
$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7
 Built:        
 OS/Arch:      linux/amd64
```

I’m not sure what’s going wrong here. Can you advise please?

### PR DESCRIPTION
**Pull request by mdevilliers**
Hey,

I've been playing with the analyze-local-images in contrib and kept getting a race whereby the image files e,g layer.tar were being sent to clair before they were untarred and available for analysis.

Essentially piping the output from `docker save` to ``tar` needs to be flushed to ensure the output is untarred correctly.

To reproduce - 

```
docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
quay.io/coreos/clair   latest              2ca9be911bd5        24 hours ago        786.2 MB
```

Run a new instance of clair

```
markdv@ubuntu:~/go/src/github.com/coreos/clair$ ./clair --db-type=bolt --db-path=/home/markdv/clair-db/database2
2015-11-24 07:11:20.627997 I | database: database at /home/markdv/clair-db/database2 does not exist yet, creating it
2015-11-24 07:11:20.632615 I | api: starting Health API on port 6061.
2015-11-24 07:11:20.633070 I | api: starting API on port 6060.
2015-11-24 07:11:20.634306 I | updater: updater service started. lock identifier: 787369ca-280e-4ed4-98aa-b929ddedbfad
2015-11-24 07:11:20.635345 I | updater: updating vulnerabilities
2015-11-24 07:11:20.635424 I | updater/fetchers: fetching Ubuntu vulneratibilities
2015-11-24 07:11:20.635484 I | updater/fetchers: fetching Debian vulneratibilities
2015-11-24 07:11:20.635618 E | updater/fetchers: could not branch Ubuntu repository: exec: "bzr": executable file not found in $PATH. output: 
2015-11-24 07:11:20.635653 E | updater: an error occured when fetching update 'Ubuntu': could not download requested ressource.
2015-11-24 07:11:20.635673 I | updater/fetchers: fetching Red Hat vulneratibilities
2015-11-24 07:11:46.302874 I | api: 201 POST /v1/layers (953.019484ms)
2015-11-24 07:11:46.306420 I | api: 201 POST /v1/layers (2.637382ms)
2015-11-24 07:11:46.466191 I | api: 201 POST /v1/layers (158.338878ms)
2015-11-24 07:11:46.616736 I | api: 201 POST /v1/layers (149.732335ms)
2015-11-24 07:11:46.708107 I | api: 201 POST /v1/layers (90.681721ms)
2015-11-24 07:11:46.712467 I | api: 201 POST /v1/layers (3.643571ms)
2015-11-24 07:11:46.716839 I | api: 201 POST /v1/layers (3.88098ms)
2015-11-24 07:11:46.717794 E | worker: layer ee6698face90f6d8c5f245a27684a626c276f41cb40ac0869478865ebe13d4af: failed to extract data from /tmp/analyze-local-image-598531890/ee6698face90f6d8c5f245a27684a626c276f41cb40ac0869478865ebe13d4af/layer.tar: the resource cannot be found
2015-11-24 07:11:46.717889 I | api: 404 POST /v1/layers (359.461µs)
```

Run the analyze-local-images using the image id 2ca9be911bd5 

```
Getting image's history
Analyzing 25 layers
- Analyzing 5679b9b90e0939cfc7943db37daceb22006f76d9a774fdf46b898827d0eeff37 at /tmp/analyze-local-image-598531890/5679b9b90e0939cfc7943db37daceb22006f76d9a774fdf46b898827d0eeff37/layer.tar
- Analyzing ea6bab360f5604439718bbcbc77b7dabc43b137a97e4fc193a8ca4f9ef25b6ad at /tmp/analyze-local-image-598531890/ea6bab360f5604439718bbcbc77b7dabc43b137a97e4fc193a8ca4f9ef25b6ad/layer.tar
- Analyzing 0f062bc856621abde5e76ca7fcb8a1915e3fb89f4aa9b0bf42df0e67d9054397 at /tmp/analyze-local-image-598531890/0f062bc856621abde5e76ca7fcb8a1915e3fb89f4aa9b0bf42df0e67d9054397/layer.tar
- Analyzing 1db7de304924df3141ab63c868d0512845b42c159e17f84c6ab4381d998f0030 at /tmp/analyze-local-image-598531890/1db7de304924df3141ab63c868d0512845b42c159e17f84c6ab4381d998f0030/layer.tar
- Analyzing 47eb4899f9cf97198db98af4a602417605bb3be31ef52262d6d4501bb2cbb79c at /tmp/analyze-local-image-598531890/47eb4899f9cf97198db98af4a602417605bb3be31ef52262d6d4501bb2cbb79c/layer.tar
- Analyzing e5d9392dfecd51a33f75ca27431306dd3754a84706fc4ee9c9dd8979d3e4ddfe at /tmp/analyze-local-image-598531890/e5d9392dfecd51a33f75ca27431306dd3754a84706fc4ee9c9dd8979d3e4ddfe/layer.tar
- Analyzing 9938bfbcc53e68c07a8ed3121dfded0978ac1ab20535b2a18aeaf6c0f75c1c5b at /tmp/analyze-local-image-598531890/9938bfbcc53e68c07a8ed3121dfded0978ac1ab20535b2a18aeaf6c0f75c1c5b/layer.tar
- Analyzing ee6698face90f6d8c5f245a27684a626c276f41cb40ac0869478865ebe13d4af at /tmp/analyze-local-image-598531890/ee6698face90f6d8c5f245a27684a626c276f41cb40ac0869478865ebe13d4af/layer.tar
2015/11/24 07:11:46 - Could not analyze layer: Got response 404 with message {"Message":"the resource cannot be found"}
```

Notice on both sides fail with "/tmp/analyze-local-image-598531890/ee6698face90f6d8c5f245a27684a626c276f41cb40ac0869478865ebe13d4af/layer.tar"

Examining the file system at a later point shows the item is there.

My fix is two fold -
1. Close the pipe which will flush to tar
2. Added a simple retryer to ensure the layer exists on disk before requesting analysis.

To reproduce I ran Clair with a new database to ensure the layer is inspected.

I think this fixes https://github.com/coreos/clair/issues/27

I hope this makes sense,

Mark

### CODE REVIEW

**Comment by Quentin-M** [comment]
Hello,

Good catch, forgot that when I hacked it.
I believe that this https://github.com/coreos/clair/commit/aaf88c38380e0f5c77b0987cca956c55c0cb10a6 would fix in a simple manner. Can you confirm?

**Comment by Quentin-M** [comment]
Hello,

Good catch, somehow forgot that when I hacked it.
I believe that this https://github.com/coreos/clair/commit/9391417b2d2761918c1a6f6f165fe1a35275cfb7 would fix in a simple manner. Can you confirm?

**Comment by mdevilliers** [comment]
Works for me and you are correct - a simpler solution.

Do you want to close my pull request?

Thanks

Mark

**Comment by Quentin-M** [comment]
Thanks for your contribution!

**Pull request closed without merging**
