### PR TITLE
pgsql: fix unchecked error

### PR DESCRIPTION
**Pull request by saromanov**
Hi! I've just fixed unchecked error. Please review it

### CODE REVIEW

**Comment by jzelinskie** [comment]
Just need to double check that this isn't intentional. Often code with caches ignores errors because caches are allowed to fail open.

**Review by KeyboardNerd — APPROVED** [review]
LGTM

**Comment by KeyboardNerd** [comment]
This is not intentional because the following code depends on the cache variable, which if is corrupted will mess up the database.

**Comment by KeyboardNerd** [comment]
I'll just merge it

**Pull request merged**
