### PR TITLE
Experimental grafeas export

### PR DESCRIPTION
**Pull request by furuholm**

### CODE REVIEW

**Comment by jzelinskie** [comment]
@furuholm I'm fairly certain we decided that this best be implemented as a separate process or a part of Grafeas. Should I close this PR?

**Comment by jzelinskie** [comment]
cc @Katee

**Comment by furuholm** [comment]
@jzelinskie That is correct. We discussed adding a proxy for Clair that could be a part of grafeas or (more likely) a standalone thing. The idea was that this proxy would intercept all requests to Clair and add what Clair finds to Grafeas. This proxy would also set up subscriptions to monitor changes in Clair.

I'd love to do it but I'm busy doing other things at the moment :( At some point I might pick this up though.

You can close this PR.

**Comment by Katee** [comment]
For Grafeas related discussion @aysylu is a great person to loop in.

**Comment by aysylu** [comment]
Thanks, @Katee! Yes, please reach out for any Grafeas related discussions. Thanks!

**Pull request closed without merging**
