### PR TITLE
ext/vulnsrc/ubuntu: updated tracker src

### LINKED ISSUE #524: could not branch Ubuntu repository
clair logs 

Feb 19 11:25:46 172.18.0.1 clair[509]: {"Event":"could not branch Ubuntu repository","Level":"error","Location":"ubuntu.go:177","Time":"2018-02-19 11:25:46.924706","error":"exit status 3","output":"bzr: ERROR: Invalid http response for http://bazaar.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master/.bzr/repository/packs/269638fd93f179ceafe5d289f42db0c1.pack: Missing the Content-Range header in a 206 range response\n"}
Feb 19 11:25:46 172.18.0.1 clair[509]: {"Event":"an error occured when fetching update","Level":"error","Location":"updater.go:220","Time":"2018-02-19 11:25:46.924851","error":"could not download requested resource","updater name":"ubuntu"}

a manual download using bzr Fails either 
with 
bzr branch lp:ubuntu-cve-tracker
or with 
bzr branch https://launchpad.net/ubuntu-cve-tracker

with the same error in the final step 
Invalid http response for http://bazaar.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master/.bzr/repository/packs/16c916fc513b214fbddf8bfb4c8f1e61.pack: Missing the Content-Range header in a 206 range Response
If I use curl the file is downloaded correctly.

.

**Environment**:
- vmware/Harbor with clair: 
- Clair client name/version: clair2.0.1
- Host OS:  photonos v1.0
- Network/Firewall setup: docker Container behind nginx and corporate firewall

### PR DESCRIPTION
**Pull request by ninjaMog**
The existing address had been switched from bzr to git. Changed address to location of current bzr master

Fixes #524

### CODE REVIEW

**Comment by brosander** [comment]
This change does the trick for us :)

```
{"Event":"finished fetching","Level":"info","Location":"updater.go:242","Time":"2018-06-29 14:18:51.910856","updater name":"ubuntu"}
```

We've created a tag release of v2.0.3 with this pr applied if anyone wants to use it:
https://hub.docker.com/r/corvana/clair/tags/

**Comment by reasonerjt** [comment]
Hi, @jzelinskie do you plan to merge this PR and produce a new release?

**Review by LorensK — APPROVED** [review]
Works for me.

**Comment by jzelinskie** [comment]
This is a pretty big deal, we can drop support for bzr in the future.

Yeah I'll merge this now and prep a release soon.

**Review by jzelinskie — APPROVED** [review]

**Comment by MackJM** [comment]
I'm not entirely sure but it looks like the new bzr url works but hasn't be updated since June 25th. I'm assuming that it means that there's no updates going to the bzr repo anymore.

**Pull request merged**
