### PR TITLE
Make source of vulnerability data configurable

### PR DESCRIPTION
**Pull request by furuholm**
This is a proposal for solving #401. I've added a new method to the Updater interface called SetSourceUrl which is invoked if the config file contains relevant source urls.

I've tried to stick to the conventions but there were a couple of things that I was not sure what to do with:

1. I have added SourceURLs as a var in updater.go. Another option would be to pass the config to fetch and use config.SourceURLs instead of SourceURLs in fetch. This would be more explicit, so I think I would prefer doing it this way, but I tried to stick to the conventions as much as possible...
2. Should I add all default urls to the sample config? I haven't but reading the comments in config.yaml.sample made me consider doing so.

### CODE REVIEW

**Comment by jzelinskie** [comment]
Hey, thanks for this PR.

I have a bunch of thoughts:
- If we're going to do something like this, I'd like dedicated sections to each vulnsrc where they can be enabled or have this source specified
- This makes the assumption that all of these upstream vulnsrcs can be mirrored
- In addition, we could build a tool that pulls down all the new vulnerabilities, and then lets you take that behind the firewall and then Clair runs an update against that neutral format.

Please add your new stuff to the sample config; I'm going to think about how to make the config file's schema make more sense with this new functionality.

Also, gofmt your code ;)

**Comment by furuholm** [comment]
Great comments!

-  Your restructuring ideas to the config file's schema makes sense.
-  I'm actually less concerned about the assumption that all of these upstream vulnsrcs can be mirrored (there **could** be a mirror for any of these, even if you couldn't set one up for yourself) and more concerned about the possibility of new updaters whose source can't be described in a URL. Then the interface would be kind of broken.
-  A tool for pulling the data in a neutral fashion sounds like a great idea. Both for complete offline mode and during development as I find some of the sources to be somewhat unreliable. Having your own "proxy" source would solve this problem. Would this be a command line tool or a file that you can serve to clair? Or both?

Have added the sources to the config file and fixed the formatting.

Cheers!

**Comment by jzelinskie** [comment]
Hey, sorry for letting this sit.

>concerned about the possibility of new updaters whose source can't be described in a URL. Then the interface would be kind of broken.

Totally agree here. Thus the hesitation to merge. Besides offline, if there isn't any other reason to make this configurable and risk having a brittle interface and config, I think this PR is ready to be closed.

>Would this be a command line tool or a file that you can serve to clair? Or both?

Ideally a tool that dumps an update file that can be carried offline and applied to an offline cluster.
The new database schema in Clair v3 (aka the master branch) theoretically should enable the capability to copy data from an online copy of Clair (or a tool that just ran the Clair updater). There is definitely some more thought that needs to go into this; since vulnerabilities and other data may be inserted in a different order,  IDs probably wouldn't match across databases. It's unlikely that the tool could be as naive as a pg_dump on a few tables, but maybe we can get something close to that.

**Comment by furuholm** [comment]
A pg_dump sounds like a good input source. In general I don't like having external tools making changes to the database though. There is too much that can go wrong as the database evolves. How about a vulnsrc extension that imports pg_dumps?

You can close the PR. Let's continue the discussion in #401.

**Pull request closed without merging**
