### PR TITLE
Notification Operation IDs

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

Change the Operation IDs to match the format of the rest of the API endpoints.

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
Dope

**Comment by ldelossa** [comment]
@alecmerdler 

fix your commit so it'll get picked up in the automated change log process.

You also need to generate new api docs. Run...
```
go generate ./...
```

and 

```
make gen-api-reference
```

at the root of the repository.

**Comment by ldelossa** [comment]
Commit message is actually fine, theres a stale regexp in the check which slipped by code review. I'll fix this today.

**Comment by ldelossa** [comment]
@alecmerdler commit check fix is merged, rebase your branch when ready.

**Review by hdonnay — APPROVED** [review]

**Pull request merged**
