### PR TITLE
Changing some minor things found while testing the project

### PR DESCRIPTION
**Pull request by crozzy**
Very minor changes

### CODE REVIEW

**Comment by ldelossa** [comment]
hey @crozzy 

You'll have to sign off on your commit along with following our commit format:

```
component: subject

body
signoff (added by git commit -s)
```

**Comment by crozzy** [comment]
> hey @crozzy
> 
> You'll have to sign off on your commit along with following our commit format:
> 
> ```
> component: subject
> 
> body
> signoff (added by git commit -s)
> ```

Sorry! Updated.

Let me know is there's something more

**Comment by ldelossa** [comment]
@crozzy that merge commit probably shouldn't be in this pr: eb95ad4164ac1e6363efe650210a42816a8de733

Can you squash it into your previous and correctly formatted commit?

**Review by ldelossa — APPROVED** [review]
Thanks!

**Pull request merged**
